- name: Check available template versions
  ansible.builtin.stat:
    path: "{{ calling_path + '/templates/' + platform + '/' + item }}"
  register: dirs
  loop:
    - "{{ sw_version }}"
    - "{{ sw_version | regex_replace('(\\.\\d+$)', '') }}"
    - "{{ sw_version | regex_replace('(\\.\\d+\\.\\d+$)', '') }}"
    - "default"

- name: Set template version
  ansible.builtin.set_fact:
    tpl_base: "{{ dirs.results[3].stat | combine(dirs.results[2].stat, dirs.results[1].stat, dirs.results[0].stat) }}"
  failed_when: not tpl_base.isdir

# - debug:
#     msg: "Using template {{ tpl_base.path }}"
