ansible_connection: ansible.netcommon.netconf
#ansible_network_os: auto
ansible_ssh_user: admin
ansible_ssh_pass: admin
ansible_host_key_checking: False
#ansible_connect_timeout: 180
#ansible_command_timeout: 180
platform: sros
#
#dcgw_serviceid_offset: 0
#dcgw_bhvpls_offset: 10000
