srl:
  _features:
    auto_itf_desc: no # generate itf-desription from LLDP state
  system:
    lldp:
      admin-state: enable
    information:
      location: "Somewhere"
      contact: "John Doe"
  network_instance: # overriding fabric intent parameters
    default:
      protocols:
        ospf:
          default:
            max-ecmp-paths: 64
            timers:
              incremental-spf-wait: 100
              lsa-generate:
                lsa-initial-wait: 50
            area:
              "0.0.0.1":
                interfaces:
                  ethernet-1/48.0:
                    hello-interval: 10
  routing_policy:
    prefix_set:
      servers:
        prefix:
          - ip-prefix: 10.0.0.0/8
            mask-length-range: "24..32"
    policy:
      export-loopbacks:
        default-action:
          policy-result: reject
        statement:
          - name: "1"
            match:
              prefix-set: loopbacks
            action:
              policy-result: accept
      lo-and-servers:
        default-action:
          policy-result: reject
        statement:
          - name: "10"
            match:
              prefix-set: loopbacks
            action:
              policy-result: accept
          - name: "20"
            match:
              prefix-set: servers
            action:
              policy-result: accept
      pass-all:
        default-action:
          policy-result: accept
        statement:
          - name: "1"
            match:
              protocol: bgp
            action:
              policy-result: accept
      pass-evpn:
        default-action:
          policy-result: accept
        statement:
          - name: "1"
            match:
              protocol: bgp-evpn
            action:
              policy-result: accept
  acl_filters:
    ipv4-filter1:
      description: "ACL for loopbacks"
      type: ipv4 # [ipv4|ipv6|mac]
      acl-entries:
        10: # sequence number
          action: accept # [accept|drop]
          match:
            destination-ip:
              prefix: 10.0.0.0/8
            source-ip:
              prefix: 0.0.0.0/0
            source-port:
              range: 1024..65000 # nr + '..' nr
            destination-port:
              range: 1024..65000 # nr + '..' nr
            protocol: tcp # nr or string
            icmp:
              code: 0 # nr
              type: echo " str"
        9999:
          action: drop
    mac-filter1:
      description: "mac filter"
      type: mac
      acl-entries:
        10:
          action: accept
          match:
            destination-mac:
              address: 00:00:00:00:00:00
              mask: 00:00:00:00:00:00
            ethertype: ipv4
            source-mac:
              address: 00:00:00:00:00:00
              mask: 00:00:00:00:00:00
sros:
  routing_policy:
    prefix_set:
      default:
        prefix:
          - ip-prefix: 0.0.0.0/0
    policy:
      export-to-underlay:
        default-action:
          policy-result: reject
        statement:
          - name: "10"
            match:
              prefix-set: default
            action:
              policy-result: reject
          - name: "20"
            match:
              prefix-set: loopbacks
              protocol: direct
            action:
              policy-result: accept
