clab-4l2s-l1:
  subinterface:
    ethernet-1/48.0:
      ipv4_address: 192.168.1.1/31
    ethernet-1/49.0:
      ipv4_address: 192.168.0.1/31
    system0.0:
      ipv4_address: 192.168.255.1/32
  network_instance:
    default:
      protocols:
        bgp:
          neighbor:
            192.168.0.0:
              peer_group: spines
            192.168.1.0:
              peer_group: spines
#
clab-4l2s-l2:
  subinterface:
    ethernet-1/48.0:
      ipv4_address: 192.168.1.3/31
    ethernet-1/49.0:
      ipv4_address: 192.168.0.3/31
    system0.0:
      ipv4_address: 192.168.255.2/32
  network_instance:
    default:
      protocols:
        bgp:
          neighbor:
            192.168.0.2:
              peer_group: spines
            192.168.1.2:
              peer_group: spines
#    subnet-2:
#      type: mac-vrf
#      mac_learning: 
#        admin_state: enable
#        age_time: 60 # never, range 60..86400: default: 300
#      mac_limit: 200 # default 250
#      proxy_arp: 
#        admin_state: enable
#        age_time: 60 # never, range 60..86400: default: never
#      ip_duplication:
#        mon_window: 10 # 1..15, default: 3
#        num_moves: 2 # 1..10, default: 5
#        hold_down_time: 15
#      mac_duplication:
#        mon_window: 10 # 1..15, default: 3
#        num_moves: 2 # 1..10, default: 5
#        hold_down_time: 15
#        action: blackhole 
##
clab-4l2s-l3:
  subinterface:
    ethernet-1/48.0:
      ipv4_address: 192.168.1.5/31
    ethernet-1/49.0:
      ipv4_address: 192.168.0.5/31
    system0.0:
      ipv4_address: 192.168.255.3/32
  network_instance:
    default:
      protocols:
        bgp:
          neighbor:
            192.168.0.4:
              peer_group: spines
            192.168.1.4:
              peer_group: spines
#
clab-4l2s-l4:
  subinterface:
    ethernet-1/48.0:
      ipv4_address: 192.168.1.7/31
    ethernet-1/49.0:
      ipv4_address: 192.168.0.7/31
    system0.0:
      ipv4_address: 192.168.255.4/32
  network_instance:
    default:
      protocols:
        bgp:
          neighbor:
            192.168.0.6:
              peer_group: spines
            192.168.1.6:
              peer_group: spines
#
clab-4l2s-s1:
  subinterface:
    ethernet-1/1.0:
      ipv4_address: 192.168.0.0/31
    ethernet-1/2.0:
      ipv4_address: 192.168.0.2/31
    ethernet-1/3.0:
      ipv4_address: 192.168.0.4/31
    ethernet-1/4.0:
      ipv4_address: 192.168.0.6/31
    system0.0:
      ipv4_address: 192.168.255.101/32
  network_instance:
    default:
      protocols:
        bgp:
          neighbor:
            192.168.0.1:
              peer_group: leafs
              peer_as: 65001
            192.168.0.3:
              peer_group: leafs
              peer_as: 65002
            192.168.0.5:
              peer_group: leafs
              peer_as: 65003
            192.168.0.7:
              peer_group: leafs
              peer_as: 65004
#
clab-4l2s-s2:
  subinterface:
    ethernet-1/1.0:
      ipv4_address: 192.168.1.0/31
    ethernet-1/2.0:
      ipv4_address: 192.168.1.2/31
    ethernet-1/3.0:
      ipv4_address: 192.168.1.4/31
    ethernet-1/4.0:
      ipv4_address: 192.168.1.6/31
    system0.0:
      ipv4_address: 192.168.255.102/32
  network_instance:
    default:
      protocols:
        bgp:
          neighbor:
            192.168.1.1:
              peer_group: leafs
              peer_as: 65001
            192.168.1.3:
              peer_group: leafs
              peer_as: 65002
            192.168.1.5:
              peer_group: leafs
              peer_as: 65003
            192.168.1.7:
              peer_group: leafs
              peer_as: 65004