ipvrf-low:
  id: 2001
  type: ip-vrf
  description: ipvrf-LOW
  snet_list:
    - macvrf: subnet-1
      gw: 10.0.1.254/24
  export_rt: 100:2001
  import_rt: 100:2001
ipvrf-med:
  id: 2002
  type: ip-vrf
  description: ipvrf-MED
  snet_list:
    - macvrf: subnet-2
      gw: 10.0.2.254/24
    - macvrf: subnet-3
      gw: 10.0.3.254/24
  export_rt: 100:2002
  import_rt: 100:2002