mh-1: # ID used to construct ESI <prefix>:<id>:<lag_id>, lag_id per rack, id farbic wide 
  lag_id: lag1
  mh_mode: all-active # all-active or single-active
  # _state: deleted 
  description: mh-1:LAG1
  interface_list:
    clab-4l2s-l1:
    - ethernet-1/20
    clab-4l2s-l2:
    - ethernet-1/20
  lacp: true
  vlan_tagging: true
  min_links: 1
mh-2: # ID used to construct ESI <prefix>:<id>:<lag_id>, lag_id per rack, id farbic wide 
  lag_id: lag2
  mh_mode: all-active
  # _state: deleted 
  description: mh-2:LAG2
  interface_list:
    clab-4l2s-l1:
    - ethernet-1/21
    clab-4l2s-l2:
    - ethernet-1/21
  lacp: true
  vlan_tagging: true
  min_links: 1
mh-3: 
  lag_id: lag1
  stby_signaling: lacp
  mh_mode: single-active
  description: mh-3:LAG1
  interface_list:
    clab-4l2s-l3:
    - ethernet-1/20
    clab-4l2s-l4:
    - ethernet-1/20
  lacp: true
  vlan_tagging: true
  min_links: 1
mh-4: 
  lag_id: lag2
  mh_mode: all-active
  # _state: deleted 
  description: mh-4:LAG2
  interface_list:
    clab-4l2s-l3:
    - ethernet-1/21
    clab-4l2s-l4:
    - ethernet-1/21
  lacp: true
  vlan_tagging: true
  min_links: 1